#!/bin/sh

# Default tmux instance
tm() {
	name="main"
	if tmux ls &> /dev/null; then
		tmux attach
	else
		tmux new -s "$name" -d
		tmux split-window -h -p 25
		tmux last-pane

		if ! [ -z "$1" ]; then
			pane="$name:0.0"
			tmux send-keys -t "$pane" "$EDITOR $1" Enter
		fi

		tmux attach-session -t "$name"
	fi
}
